version: '3.9'

services:
  main:
    container_name: main
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '3001:3001'
      - '9229:9229'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - todo_net
    restart: unless-stopped
  database:
    container_name: database
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: JavaDeveloper
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo_net
    tty: true
    restart: unless-stopped

volumes:
  pgdata:
  server:

networks:
  todo_net:
    driver: bridge