services:
  database-todo:
    container_name: database-todo
    image: postgres:14-alpine3.16
    environment:
      POSTGRES_PASSWORD: JavaDeveloper
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net
    tty: true
    restart: always
  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    links:
      - database-todo
    ports:
      - '8080:8080'
    networks:
      - todo-net
    restart: on-failure  
  node-server:
    container_name: node-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-todo
    networks:
      - todo-net
    restart: unless-stopped  

volumes:
  pgdata:
    driver: local
  server: {}

networks:
  todo-net:
    driver: bridge