version: '3.9'

services:
  node_server:
    container_name: node_server
    environment:
      NODE_ENV: development
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev  
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database_todo
    networks:
      - todo_net
    restart: unless-stopped
  database_todo:
    container_name: database_todo
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: JavaDeveloper
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo_net
    tty: true
    restart: always
  adminer:
    image: adminer
    container_name: adminer-docker
    depends_on:
      - database_todo
    ports:
      - '8080:8080'
    networks:
      - todo_net
    restart: on-failure  

volumes:
  pgdata:
  server: {}

networks:
  todo_net:
    driver: bridge