POST http://localhost:3001/api/auth/sign-up
Content-Type: application/json

{
  "name": "Tomas",
  "surname": "Andersen",
  "email": "Hero1@gmail.com",
  "birthday": "1993-10-12",
  "isMale": false,
  "password": "123Admin!"
}
