POST http://localhost:3001/api/auth/sign-up
Content-Type: application/json

{
  "name": "Tomas",
  "surname": "Andersen",
  "email": "test8@gmail.com",
  "birthday": "1993-10-10",
  "isMale": true,
  "password": "123Admin!"
}
